//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team5Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch_Admin()
        {
            this.Vehicle_Availability = new HashSet<Vehicle_Availability>();
            this.Branch_Vehicle_Request = new HashSet<Branch_Vehicle_Request>();
        }
    
        public string Branch_id { get; set; }
        public string Password { get; set; }
        public string Branch_Location { get; set; }
        public string Address { get; set; }
        public string Mail_id { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
        public string Role_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Availability> Vehicle_Availability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch_Vehicle_Request> Branch_Vehicle_Request { get; set; }
    }
}
