//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team5Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Profile()
        {
            this.Customer_Vehicle_Booking1 = new HashSet<Customer_Vehicle_Booking1>();
        }
    
        public string Customer_id { get; set; }
        public string Customer_name { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Address { get; set; }
        public string Mail_id { get; set; }
        public string Phone { get; set; }
        public string Occupation { get; set; }
        public string Status { get; set; }
        public string Role_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Vehicle_Booking1> Customer_Vehicle_Booking1 { get; set; }
    }
}
